dist: xenial

language: python
python:
  - "3.8.5"

notifications:
  email:
    - kebedey@renci.org


# command to install dependencies
install:
  - pip install -r requirements.txt

env:
  global:
    - PYTHONPATH=$PWD

# command to run tests
script:
  - pytest -p no:warnings tests

after_success:
  - coveralls
